copyright = "© Larissa Nunes da Costa"
defaultContentLanguage = "en"
disableKinds = ["taxonomy"]
enableRobotsTXT = true
languageCode = "en"
timeZone = "Europe/Berlin"
timeout = "120s"
title = "Atelier da Lari"

[params]
  defaultTheme = "dark"
  description = "Example site for hugo-theme-gallery"
  title = "Atelier da Lari"
  [params.author]
    email = "user@example.com"
    name = "Larissa Nunes da Costa"
  [params.socialIcons]
    #facebook = "https://www.facebook.com/"
    instagram = "https://www.instagram.com/lari.ncosta/"
    #github = "https://github.com/nicokaiser/hugo-theme-gallery/"
    #youtube = "https://www.youtube.com/"
    email = "larissadacosta.aquarela@gmail.com"
    #website = "https://example.com"
    #mastodon = "https://example.com"
    #pixelfed = "https://example.com"
    #mixcloud = "https://mixcloud.com"
  [params.gallery]
    #boxSpacing = 10
    #targetRowHeight = 288
    #targetRowHeightTolerance = 0.25

[outputs]
  home = ["HTML", "RSS"]
  page = ["HTML"]
  section = ["HTML"]

[imaging]
  quality = 75
  resampleFilter = "CatmullRom"
  [imaging.exif]
    disableDate = false
    disableLatLong = true
    includeFields = "ImageDescription|Orientation"

[module]
  [module.hugoVersion]
    min = "0.121.2"
  [[module.imports]]
    path = "github.com/nicokaiser/hugo-theme-gallery/v4"

[menu]
  [[menu.footer]]
    name = "GitHub"
    url = "https://github.com/ggoetten"
    weight = 3

[services]
  [services.rss]
    limit = 100
